/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package Interfaz;

import Modelo.Sistema;

/**
 *
 * @author juand
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());
    private Sistema sistema;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(Sistema unSistema) {
        sistema = unSistema;
        initComponents();
        addWindowListener(new java.awt.event.WindowAdapter() { //guardar al salir: boton "x"
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                sistema.guardarSistema();
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menuVentanas = new javax.swing.JMenu();
        datosMenu = new javax.swing.JMenu();
        clientesMenu = new javax.swing.JMenuItem();
        funcionariosMenu = new javax.swing.JMenuItem();
        tarifaMenu = new javax.swing.JMenuItem();
        paquetesMenu = new javax.swing.JMenu();
        ingresoMenu = new javax.swing.JMenuItem();
        envioMenu = new javax.swing.JMenuItem();
        recepcionMenu = new javax.swing.JMenuItem();
        reportesMenu = new javax.swing.JMenu();
        paquetesPorEstadoMenu = new javax.swing.JMenuItem();
        consultaPorClienteMenu = new javax.swing.JMenuItem();
        logTransaccionesMenu = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuVentanas.setMnemonic('f');
        menuVentanas.setText("Ventanas");

        datosMenu.setText("Datos");

        clientesMenu.setText("Clientes");
        clientesMenu.addActionListener(this::clientesMenuActionPerformed);
        datosMenu.add(clientesMenu);

        funcionariosMenu.setText("Funcionarios");
        funcionariosMenu.addActionListener(this::funcionariosMenuActionPerformed);
        datosMenu.add(funcionariosMenu);

        tarifaMenu.setText("Tarifa");
        tarifaMenu.addActionListener(this::tarifaMenuActionPerformed);
        datosMenu.add(tarifaMenu);

        menuVentanas.add(datosMenu);

        paquetesMenu.setText("Paquetes");

        ingresoMenu.setText("Ingreso");
        ingresoMenu.addActionListener(this::ingresoMenuActionPerformed);
        paquetesMenu.add(ingresoMenu);

        envioMenu.setText("Envio");
        envioMenu.addActionListener(this::envioMenuActionPerformed);
        paquetesMenu.add(envioMenu);

        recepcionMenu.setText("Recepcion");
        recepcionMenu.addActionListener(this::recepcionMenuActionPerformed);
        paquetesMenu.add(recepcionMenu);

        menuVentanas.add(paquetesMenu);

        reportesMenu.setText("Reportes");
        reportesMenu.addActionListener(this::reportesMenuActionPerformed);

        paquetesPorEstadoMenu.setText("Paquetes por Estado");
        paquetesPorEstadoMenu.addActionListener(this::paquetesPorEstadoMenuActionPerformed);
        reportesMenu.add(paquetesPorEstadoMenu);

        consultaPorClienteMenu.setText("Consulta por Cliente");
        consultaPorClienteMenu.addActionListener(this::consultaPorClienteMenuActionPerformed);
        reportesMenu.add(consultaPorClienteMenu);

        logTransaccionesMenu.setText("Log de transacciones");
        logTransaccionesMenu.addActionListener(this::logTransaccionesMenuActionPerformed);
        reportesMenu.add(logTransaccionesMenu);

        menuVentanas.add(reportesMenu);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(this::exitMenuItemActionPerformed);
        menuVentanas.add(exitMenuItem);

        menuBar.add(menuVentanas);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        sistema.guardarSistema(); //guardar al salir desde menu
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void clientesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesMenuActionPerformed
        VentanaCliente ventana = new VentanaCliente(sistema);
        ventana.setVisible(true);
    }//GEN-LAST:event_clientesMenuActionPerformed

    private void funcionariosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionariosMenuActionPerformed
        VentanaFuncionario ventana = new VentanaFuncionario(sistema);
        ventana.setVisible(true);
    }//GEN-LAST:event_funcionariosMenuActionPerformed

    private void tarifaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifaMenuActionPerformed
        VentanaTarifas ventana = new VentanaTarifas(sistema);
        ventana.setVisible(true);
    }//GEN-LAST:event_tarifaMenuActionPerformed

    private void ingresoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoMenuActionPerformed
        VentanaIngresoPaquetes ventana = new VentanaIngresoPaquetes(sistema);
        ventana.setVisible(true);
    }//GEN-LAST:event_ingresoMenuActionPerformed

    private void envioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envioMenuActionPerformed
        VentanaEnvio ventana = new VentanaEnvio(sistema);
        ventana.setVisible(true);
    }//GEN-LAST:event_envioMenuActionPerformed

    private void recepcionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recepcionMenuActionPerformed
        VentanaRecepcion ventana = new VentanaRecepcion(sistema);
        ventana.setVisible(true);
    }//GEN-LAST:event_recepcionMenuActionPerformed

    private void reportesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesMenuActionPerformed
        
    }//GEN-LAST:event_reportesMenuActionPerformed

    private void consultaPorClienteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaPorClienteMenuActionPerformed
        VentanaConsultaPorCliente ventana = new VentanaConsultaPorCliente(sistema);
        ventana.setVisible(true);
    }//GEN-LAST:event_consultaPorClienteMenuActionPerformed

    private void logTransaccionesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logTransaccionesMenuActionPerformed
        VentanaLogTransacciones ventana = new VentanaLogTransacciones(sistema);
        ventana.setVisible(true);
    }//GEN-LAST:event_logTransaccionesMenuActionPerformed

    private void paquetesPorEstadoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paquetesPorEstadoMenuActionPerformed
        VentanaPaquetesPorEstado ventana = new VentanaPaquetesPorEstado(sistema);
        ventana.setVisible(true);
    }//GEN-LAST:event_paquetesPorEstadoMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem clientesMenu;
    private javax.swing.JMenuItem consultaPorClienteMenu;
    private javax.swing.JMenu datosMenu;
    private javax.swing.JMenuItem envioMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem funcionariosMenu;
    private javax.swing.JMenuItem ingresoMenu;
    private javax.swing.JMenuItem logTransaccionesMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuVentanas;
    private javax.swing.JMenu paquetesMenu;
    private javax.swing.JMenuItem paquetesPorEstadoMenu;
    private javax.swing.JMenuItem recepcionMenu;
    private javax.swing.JMenu reportesMenu;
    private javax.swing.JMenuItem tarifaMenu;
    // End of variables declaration//GEN-END:variables

}
