/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Modelo.Sistema;
import Modelo.Funcionario;
import Modelo.Observador;
import java.util.ArrayList;
/**
 *
 * @author juand
 */
public class VentanaFuncionario extends javax.swing.JFrame implements Observador{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaFuncionario.class.getName());
    private Sistema sistema;
    /**
     * Creates new form VentanaFuncionario
     */
    public VentanaFuncionario(Sistema unSistema) {
        initComponents();
        sistema = unSistema;
        sistema.agregarObservador(this);
        cargarListaFuncionarios();
    }
    
    public void cargarListaFuncionarios(){
        ArrayList<Funcionario> listaOrdenada = sistema.obtenerFuncionariosOrdenados();
        lstListaFuncionarios.setListData(listaOrdenada.toArray(new Funcionario[0]));
        if (listaOrdenada.isEmpty()) {
            lblFuncionariosVacia.setVisible(true);
            jNombre.setVisible(false);
            jCelular.setVisible(false);
            jNumeroFuncionario.setVisible(false);
            jIngreso.setVisible(false);
            jCargo.setVisible(false);
        } else {
            lblFuncionariosVacia.setVisible(false);
            jNombre.setVisible(true);
            jCelular.setVisible(true);
            jNumeroFuncionario.setVisible(true);
            jIngreso.setVisible(true);
            jCargo.setVisible(true);
        }
    }
    
    @Override
    public void actualizar(){
        cargarListaFuncionarios();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstListaFuncionarios = new javax.swing.JList<>();
        btnAltaFuncionario = new javax.swing.JButton();
        jEditarFuncionario = new javax.swing.JButton();
        jNombre = new javax.swing.JTextField();
        jCelular = new javax.swing.JTextField();
        jNumeroFuncionario = new javax.swing.JTextField();
        jIngreso = new javax.swing.JTextField();
        lblFuncionariosVacia = new javax.swing.JLabel();
        jCargo = new javax.swing.JLabel();
        jFiltrar = new javax.swing.JButton();
        jFiltroCargo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Funcionarios");

        lstListaFuncionarios.addListSelectionListener(this::lstListaFuncionariosValueChanged);
        jScrollPane1.setViewportView(lstListaFuncionarios);

        btnAltaFuncionario.setText("Registrar Funcionario");
        btnAltaFuncionario.addActionListener(this::btnAltaFuncionarioActionPerformed);

        jEditarFuncionario.setText("Editar Funcionario");
        jEditarFuncionario.addActionListener(this::jEditarFuncionarioActionPerformed);

        jNombre.setText("Nombre");

        jCelular.setText("Celular");

        jNumeroFuncionario.setText("Numero Funcionario");

        jIngreso.setText("Año Ingreso");

        lblFuncionariosVacia.setText("Lista de funcionarios VACÍA");
        lblFuncionariosVacia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCargo.setText("Cargo");

        jFiltrar.setText("Filtrar por Cargo");
        jFiltrar.addActionListener(this::jFiltrarActionPerformed);

        jFiltroCargo.setText("Cargo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNumeroFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jNombre)
                            .addComponent(jCelular)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCargo))
                                .addGap(0, 10, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFuncionariosVacia)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAltaFuncionario)
                                            .addComponent(jFiltrar))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jFiltroCargo)
                                            .addComponent(jEditarFuncionario))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jNumeroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCargo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFuncionariosVacia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAltaFuncionario)
                    .addComponent(jEditarFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFiltrar)
                    .addComponent(jFiltroCargo))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 380, 280);

        setBounds(0, 0, 416, 312);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaFuncionarioActionPerformed
        VentanaAltaFuncionario ventanaAlta = new VentanaAltaFuncionario(sistema, this);
        ventanaAlta.setVisible(true);
    }//GEN-LAST:event_btnAltaFuncionarioActionPerformed

    private void jEditarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarFuncionarioActionPerformed
        Funcionario funcionarioSeleccionado = lstListaFuncionarios.getSelectedValue();
        if(funcionarioSeleccionado == null){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un funcionario de la lista",
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }else{
            String numeroTexto = jNumeroFuncionario.getText();
            String añoTexto = jIngreso.getText();
            boolean datosNumericosValidos = sistema.verificarCaracteresNumericos(numeroTexto) && sistema.verificarCaracteresNumericos(añoTexto);
            if(datosNumericosValidos){
                int numero = Integer.parseInt(numeroTexto);
                int año = Integer.parseInt(añoTexto);
                boolean modificado = sistema.modificarFuncionario(funcionarioSeleccionado.getNombre(),
                        jNombre.getText(), jCelular.getText(), numero, año);
                if(modificado){
                    javax.swing.JOptionPane.showMessageDialog(this, "Funcionario modificado correctamente");
                    cargarListaFuncionarios();
                }else{
                    javax.swing.JOptionPane.showMessageDialog(this, "No se pudo modificar el funcionario. "
                            + "Verifique que el nombre sea valido y unico", "Error",
                            javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }else{
                javax.swing.JOptionPane.showMessageDialog(this,
                        "El número de funcionario y el año de ingreso deben ser numéricos.",
                        "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jEditarFuncionarioActionPerformed

    private void lstListaFuncionariosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstListaFuncionariosValueChanged
        Funcionario funcionarioSeleccionado = lstListaFuncionarios.getSelectedValue();
        if(funcionarioSeleccionado != null){
            jNombre.setText(funcionarioSeleccionado.getNombre());
            jCelular.setText(funcionarioSeleccionado.getCelular());
            jNumeroFuncionario.setText(String.valueOf(funcionarioSeleccionado.getNumeroFuncionario()));
            jIngreso.setText(String.valueOf(funcionarioSeleccionado.getAñoIngreso()));
        }
    }//GEN-LAST:event_lstListaFuncionariosValueChanged

    private void jFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFiltrarActionPerformed
        String cargoFiltro = jFiltroCargo.getText().trim();
        if (cargoFiltro.isEmpty()) {
            cargarListaFuncionarios();
        } else {
            ArrayList<Funcionario> filtrados = sistema.buscarFuncionariosPorCargo(cargoFiltro);
            lstListaFuncionarios.setListData(filtrados.toArray(new Funcionario[0]));
        } 
    }//GEN-LAST:event_jFiltrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new VentanaFuncionario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaFuncionario;
    private javax.swing.JLabel jCargo;
    private javax.swing.JTextField jCelular;
    private javax.swing.JButton jEditarFuncionario;
    private javax.swing.JButton jFiltrar;
    private javax.swing.JLabel jFiltroCargo;
    private javax.swing.JTextField jIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jNombre;
    private javax.swing.JTextField jNumeroFuncionario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFuncionariosVacia;
    private javax.swing.JList<Funcionario> lstListaFuncionarios;
    // End of variables declaration//GEN-END:variables
}
