/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Modelo.Cliente;
import Modelo.Sistema;
import Modelo.Observador;
import Modelo.Paquete;
import java.util.ArrayList;
/**
 *
 * @author juand
 */
public class VentanaConsultaPorCliente extends javax.swing.JFrame implements Observador{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaConsultaPorCliente.class.getName());
    private Sistema sistema;
    /**
     * Creates new form VentanaConsultaPorCliente
     */
    public VentanaConsultaPorCliente(Sistema unSistema) {
        initComponents();
        sistema = unSistema;
        sistema.agregarObservador(this);
        cargarListaClientes();
        cargarListaPaquetes();
    }
    public void cargarListaClientes(){
        ArrayList<Cliente> clientesOrdenados;
        clientesOrdenados = sistema.obtenerClientesOrdenados();
        lstListaClientes.setListData(clientesOrdenados.toArray(new Cliente[0]));
        if (clientesOrdenados.isEmpty()) {
            lblClientesVacia.setVisible(true);
        } else {
            lblClientesVacia.setVisible(false);
        }
    }
    public void cargarListaPaquetes(){
        String[] resultado;
        Cliente clienteSeleccionado = lstListaClientes.getSelectedValue();
        boolean haySeleccion = (clienteSeleccionado != null);
        if(haySeleccion){
            int cantidadPendientes = sistema.contarPaquetesPorClienteYEstado(clienteSeleccionado, "Pendiente");
            int cantidadEnviados = sistema.contarPaquetesPorClienteYEstado(clienteSeleccionado, "Enviado");
            int cantidadRecibidos = sistema.contarPaquetesPorClienteYEstado(clienteSeleccionado, "Recibido");
            resultado = new String[3];
            resultado[0] = "Pendiente: " + cantidadPendientes;
            resultado[1] = "Enviado: " + cantidadEnviados;
            resultado[2] = "Recibido: " + cantidadRecibidos;
        } else {
            resultado = new String[0];
        }
        lstTotalPaquetes.setListData(resultado);
    }
    
    @Override
    public void actualizar(){
        cargarListaClientes();
        cargarListaPaquetes();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstListaClientes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstTotalPaquetes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        lblClientesVacia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lstListaClientes.addListSelectionListener(this::lstListaClientesValueChanged);
        jScrollPane1.setViewportView(lstListaClientes);

        jScrollPane2.setViewportView(lstTotalPaquetes);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Consulta por Cliente");

        lblClientesVacia.setText("Lista Clientes VACÍA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClientesVacia)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblClientesVacia)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 640, 470);

        setBounds(0, 0, 675, 496);
    }// </editor-fold>//GEN-END:initComponents

    private void lstListaClientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstListaClientesValueChanged
        cargarListaPaquetes();
    }//GEN-LAST:event_lstListaClientesValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new VentanaConsultaPorCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClientesVacia;
    private javax.swing.JList<Cliente> lstListaClientes;
    private javax.swing.JList<String> lstTotalPaquetes;
    // End of variables declaration//GEN-END:variables
}
