
package Interfaz;
import Modelo.Sistema;
import Modelo.Cliente;
import Modelo.Departamento;
import Modelo.Observador;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author juand
 */
public class VentanaIngresoPaquetes extends javax.swing.JFrame implements Observador{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaIngresoPaquetes.class.getName());
    private Sistema sistema;
    private int precioCalculado;
    /**
     * Creates new form VentanaIngresoPaquetes
     */
    public VentanaIngresoPaquetes(Sistema unSistema) {
        initComponents();
        sistema = unSistema;
        sistema.agregarObservador(this);
        cargarListas();
    }
    
    private void cargarListas(){
        ArrayList<Cliente> clientes = sistema.obtenerClientesOrdenados();
        lstListaClientes.setListData(clientes.toArray(new Cliente[0]));
        if (clientes.isEmpty()) {
            lblClientesVacia.setVisible(true);
        } else {
            lblClientesVacia.setVisible(false);
        }
        ArrayList<Departamento> departamentos = sistema.getListaDepartamentos();
        lstListaDepartamentos.setListData(departamentos.toArray(new Departamento[0]));
        if (departamentos.isEmpty()) {
            lblDepartamentosVacia.setVisible(true);
        } else {
            lblDepartamentosVacia.setVisible(false);
        }
    }
    
    @Override
    public void actualizar(){
        cargarListas();
    }    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jIdentificador = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstListaClientes = new javax.swing.JList<>();
        jFecha = new javax.swing.JFormattedTextField();
        jDestinatario = new javax.swing.JTextField();
        jDireccion = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstListaDepartamentos = new javax.swing.JList<>();
        jPesoEnGramos = new javax.swing.JTextField();
        btnCalcularPrecio = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        lblPrecioCalculado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblClientesVacia = new javax.swing.JLabel();
        lblDepartamentosVacia = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jIdentificador.setColumns(15);
        jIdentificador.setText("Identificador");
        jIdentificador.addActionListener(this::jIdentificadorActionPerformed);

        jScrollPane1.setViewportView(lstListaClientes);

        jFecha.setColumns(15);
        jFecha.setText("Fecha");

        jDestinatario.setColumns(15);
        jDestinatario.setText("Destinatario");

        jDireccion.setColumns(15);
        jDireccion.setText("Direccion");

        jScrollPane2.setViewportView(lstListaDepartamentos);

        jPesoEnGramos.setColumns(15);
        jPesoEnGramos.setText("Peso en gramos");

        btnCalcularPrecio.setText("Calcular Precio");
        btnCalcularPrecio.addActionListener(this::btnCalcularPrecioActionPerformed);

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);

        lblPrecioCalculado.setText("$0");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Ingreso de Paquetes");

        lblClientesVacia.setText("Lista Clientes VACÍA");

        lblDepartamentosVacia.setText("Lista Departamentos VACÍA");

        jLabel2.setText("Ingrese un identificador:");

        jLabel3.setText("Ingrese fecha:");

        jLabel4.setText("Ingrese destinatario:");

        jLabel5.setText("Ingrese dirección:");

        jLabel6.setText("Ingrese el peso en gramos:");

        jLabel7.setText("Precio:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConfirmar)
                            .addComponent(btnCalcularPrecio)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(lblDepartamentosVacia)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblClientesVacia)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFecha, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDestinatario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPrecioCalculado)
                                        .addGap(12, 12, 12))
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPesoEnGramos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblClientesVacia)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDepartamentosVacia)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPesoEnGramos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularPrecio)
                    .addComponent(lblPrecioCalculado)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfirmar)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIdentificadorActionPerformed

    private void btnCalcularPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularPrecioActionPerformed
        String identificador = jIdentificador.getText();
        String fecha = jFecha.getText();
        String destinatario = jDestinatario.getText();
        String pesoTexto = jPesoEnGramos.getText();

        Cliente clienteSeleccionado = lstListaClientes.getSelectedValue();
        Departamento departamentoSeleccionado = lstListaDepartamentos.getSelectedValue();

        boolean camposCompletos = (clienteSeleccionado != null) && (departamentoSeleccionado != null) && (!identificador.isEmpty()) && (!fecha.isEmpty()) && (!destinatario.isEmpty()) && (!pesoTexto.isEmpty());

        if (camposCompletos) {
            boolean pesoValido = sistema.verificarCaracteresNumericos(pesoTexto);
            if (pesoValido) {
                int peso = Integer.parseInt(pesoTexto);
                precioCalculado = sistema.calcularTarifa(peso, departamentoSeleccionado);
                lblPrecioCalculado.setText("$" + precioCalculado);
                btnConfirmar.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this,
                        "El peso debe ser numérico.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Debe completar todos los campos y seleccionar un cliente y departamento.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularPrecioActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        String identificador = jIdentificador.getText();
        Cliente cliente = lstListaClientes.getSelectedValue();
        String fecha = jFecha.getText();
        String destinatario = jDestinatario.getText();
        String pesoTexto = jPesoEnGramos.getText();
        Departamento departamentoSeleccionado = lstListaDepartamentos.getSelectedValue();
        if (cliente != null && departamentoSeleccionado != null) {
            int peso = Integer.parseInt(pesoTexto);
            boolean registrado = sistema.registrarPaquete(identificador, cliente, fecha, destinatario, departamentoSeleccionado, peso, precioCalculado);
            if (registrado) {
                if(VentanaIngresoPaquetesSig.getInstancia() == null){
                    VentanaIngresoPaquetesSig ventanaSig = new VentanaIngresoPaquetesSig(sistema);
                    ventanaSig.setVisible(true);
                }
                jIdentificador.setText("");
                jDestinatario.setText("");
                jPesoEnGramos.setText("");
                lblPrecioCalculado.setText("$0");
                btnConfirmar.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this,
                        "No se pudo registrar el paquete. El identificador ya existe o es inválido.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar un cliente y un departamento antes de confirmar.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new VentanaIngresoPaquetes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularPrecio;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField jDestinatario;
    private javax.swing.JTextField jDireccion;
    private javax.swing.JFormattedTextField jFecha;
    private javax.swing.JTextField jIdentificador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jPesoEnGramos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClientesVacia;
    private javax.swing.JLabel lblDepartamentosVacia;
    private javax.swing.JLabel lblPrecioCalculado;
    private javax.swing.JList<Cliente> lstListaClientes;
    private javax.swing.JList<Departamento> lstListaDepartamentos;
    // End of variables declaration//GEN-END:variables
}
