
package Interfaz;
import Modelo.Envio;
import Modelo.Funcionario;
import Modelo.Observador;
import Modelo.Paquete;
import Modelo.Sistema;
import Modelo.Zona;
import java.util.ArrayList;
/**
 *
 * @author juand
 */
public class VentanaEnvio extends javax.swing.JFrame implements Observador{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaEnvio.class.getName());
    private Sistema sistema;
    private ArrayList<Paquete> paquetesAEnviar;
    private ArrayList<Paquete> paquetesDisponibles;
    private Zona zonaActual;
    /**
     * Creates new form VentanaEnvio
     */
    public VentanaEnvio(Sistema unSistema) {
        initComponents();
        sistema = unSistema;
        sistema.agregarObservador(this);
        paquetesAEnviar = new ArrayList<Paquete>();
        cargarDatosIniciales();
    }
    private void cargarDatosIniciales(){
        ArrayList<Funcionario> funcionarios = sistema.obtenerFuncionariosOrdenados();
        Funcionario[] arregloFuncionarios = funcionarios.toArray(new Funcionario[0]); //setListData no acepta ArrayList -> .toArray()
        lstListaFuncionarios.setListData(arregloFuncionarios);
        ArrayList<Zona> zonas = sistema.getListaZonas();
        Zona[] arregloZonas = zonas.toArray(new Zona[0]); //setListData no acepta ArrayList -> .toArray()
        lstListaZonas.setListData(arregloZonas);
        lstListaPaquetesDisponibles.setListData(new Paquete[0]);
        lstListaPaquetesAEnviar.setListData(new Paquete[0]);
        int numeroEnvio = Envio.getContadorEnvios()+1;
        jEnvioNumero.setText("Envio numero: "+numeroEnvio);
        
        if (funcionarios.isEmpty()) {
            lblFuncionariosVacia.setVisible(true);
        } else {
            lblFuncionariosVacia.setVisible(false);
        }
        if (zonas.isEmpty()) {
            lblZonasVacia.setVisible(true);
        } else {
            lblZonasVacia.setVisible(false);
        }
        actualizarTotales();
    }
    
    private void actualizarTotales(){
        int cantidad = paquetesAEnviar.size();
        int pesoTotalEnGramos = sistema.calcularPesoTotal(paquetesAEnviar);
        int montoTotal = sistema.calcularMontoTotal(paquetesAEnviar);
        int kg = pesoTotalEnGramos / 1000;
        int gramos = pesoTotalEnGramos % 1000;

        jCantidadPaquetes.setText("Cantidad de paquetes: " + cantidad);
        jPesoTotal.setText("Peso: " + kg + " kg, " + gramos + " gramos");
        jMontoTotal.setText("Monto: $" + montoTotal);
    }
    
    @Override
    public void actualizar(){
        cargarDatosIniciales();
        actualizarTotales();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstListaFuncionarios = new javax.swing.JList<>();
        jEnvioNumero = new javax.swing.JTextField();
        jFechaEnvio = new javax.swing.JFormattedTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstListaZonas = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstListaPaquetesAEnviar = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstListaPaquetesDisponibles = new javax.swing.JList<>();
        btnConfirmarEnvio = new javax.swing.JButton();
        btnAgregarPaquete = new javax.swing.JButton();
        btnQuitarPaquete = new javax.swing.JButton();
        jCantidadPaquetes = new javax.swing.JLabel();
        jPesoTotal = new javax.swing.JLabel();
        jMontoTotal = new javax.swing.JLabel();
        lblFuncionariosVacia = new javax.swing.JLabel();
        lblZonasVacia = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Envio");
        jScrollPane5.setViewportView(jTextArea1);

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Envios");

        jScrollPane1.setViewportView(lstListaFuncionarios);

        jEnvioNumero.setText("Envio Numero:");

        jFechaEnvio.setText("Fecha Envio");

        lstListaZonas.addListSelectionListener(this::lstListaZonasValueChanged);
        jScrollPane3.setViewportView(lstListaZonas);

        lstListaPaquetesAEnviar.setPreferredSize(new java.awt.Dimension(300, 150));
        lstListaPaquetesAEnviar.addListSelectionListener(this::lstListaPaquetesAEnviarValueChanged);
        jScrollPane4.setViewportView(lstListaPaquetesAEnviar);

        lstListaPaquetesDisponibles.setPreferredSize(new java.awt.Dimension(300, 150));
        jScrollPane2.setViewportView(lstListaPaquetesDisponibles);

        btnConfirmarEnvio.setText("Confirmar");
        btnConfirmarEnvio.addActionListener(this::btnConfirmarEnvioActionPerformed);

        btnAgregarPaquete.setText("Agregar");
        btnAgregarPaquete.addActionListener(this::btnAgregarPaqueteActionPerformed);

        btnQuitarPaquete.setText("Quitar");
        btnQuitarPaquete.addActionListener(this::btnQuitarPaqueteActionPerformed);

        jCantidadPaquetes.setText("Cantidad Paquetes");

        jPesoTotal.setText("Peso:");

        jMontoTotal.setText("Monto:");

        lblFuncionariosVacia.setText("Lista Funcionarios VACÍA");

        lblZonasVacia.setText("Lista Zonas VACÍA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCantidadPaquetes)
                .addGap(238, 238, 238))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFechaEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(jEnvioNumero)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFuncionariosVacia)
                            .addComponent(lblZonasVacia)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(422, 422, 422)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPesoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(156, 156, 156))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAgregarPaquete)
                                    .addComponent(btnQuitarPaquete))
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(309, 309, 309)
                                .addComponent(btnConfirmarEnvio)))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFuncionariosVacia)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jEnvioNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFechaEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblZonasVacia)
                .addGap(7, 7, 7)
                .addComponent(jCantidadPaquetes)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(btnAgregarPaquete)
                            .addGap(26, 26, 26)
                            .addComponent(btnQuitarPaquete)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPesoTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMontoTotal)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmarEnvio)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 860, 860);

        setBounds(0, 0, 911, 892);
    }// </editor-fold>//GEN-END:initComponents

    private void lstListaZonasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstListaZonasValueChanged
        Zona zonaSeleccionada = lstListaZonas.getSelectedValue();
        boolean cambioDeZona = zonaSeleccionada != null && zonaSeleccionada != zonaActual;
        boolean cambioDeZonaInvalido = cambioDeZona && !paquetesAEnviar.isEmpty();
        boolean cambioDeZonaValido = cambioDeZona && paquetesAEnviar.isEmpty();
        if (cambioDeZonaInvalido) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ya hay paquetes seleccionados de la zona " + zonaActual + ". Quite todos los paquetes antes de cambiar de zona.");
            lstListaZonas.setSelectedValue(zonaActual, true);
        } else if (cambioDeZonaValido) {
            zonaActual = zonaSeleccionada;
            paquetesDisponibles = sistema.obtenerPaquetesPendientesPorZona(zonaSeleccionada);
            Paquete[] arregloPendientes = paquetesDisponibles.toArray(new Paquete[0]); //setListData no acepta ArrayList -> .toArray(). Ademas hay que hacer cast explicito (new Paquete)
            lstListaPaquetesDisponibles.setListData(arregloPendientes);
        }
    }//GEN-LAST:event_lstListaZonasValueChanged

    private void btnAgregarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPaqueteActionPerformed
        Paquete paqueteSeleccionado = lstListaPaquetesDisponibles.getSelectedValue();
        if(paqueteSeleccionado !=null){
            paquetesAEnviar.add(paqueteSeleccionado);
            paquetesDisponibles.remove(paqueteSeleccionado);
            Paquete[] arregloDisponibles = paquetesDisponibles.toArray(new Paquete[0]);
            lstListaPaquetesDisponibles.setListData(arregloDisponibles);
            Paquete[] arregloAEnviar = paquetesAEnviar.toArray(new Paquete[0]);
            lstListaPaquetesAEnviar.setListData(arregloAEnviar);
            actualizarTotales();
        }
    }//GEN-LAST:event_btnAgregarPaqueteActionPerformed

    private void btnQuitarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarPaqueteActionPerformed
        Paquete paqueteSeleccionado = lstListaPaquetesAEnviar.getSelectedValue();
        if (paqueteSeleccionado != null) {
            paquetesAEnviar.remove(paqueteSeleccionado);
            paquetesDisponibles.add(paqueteSeleccionado);
            Paquete[] arregloAEnviar = paquetesAEnviar.toArray(new Paquete[0]);
            lstListaPaquetesAEnviar.setListData(arregloAEnviar);
            Paquete[] arregloDisponibles = paquetesDisponibles.toArray(new Paquete[0]);
            lstListaPaquetesDisponibles.setListData(arregloDisponibles);
            if (paquetesAEnviar.isEmpty()) {
                zonaActual = null;
            }
            actualizarTotales();
        }
    }//GEN-LAST:event_btnQuitarPaqueteActionPerformed

    private void lstListaPaquetesAEnviarValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstListaPaquetesAEnviarValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstListaPaquetesAEnviarValueChanged

    private void btnConfirmarEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarEnvioActionPerformed
        Funcionario funcionarioSeleccionado = lstListaFuncionarios.getSelectedValue();
        String fecha = jFechaEnvio.getText();
        Zona zonaSeleccionada = lstListaZonas.getSelectedValue();

        if (funcionarioSeleccionado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un funcionario");
        } else if (fecha.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar la fecha");
        } else if (zonaSeleccionada == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una zona");
        } else if (paquetesAEnviar.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un paquete");
        } else {
            sistema.registrarEnvio(fecha, zonaSeleccionada, funcionarioSeleccionado, paquetesAEnviar);
            javax.swing.JOptionPane.showMessageDialog(this, "Envío registrado con éxito");
            this.dispose();
        }
    }//GEN-LAST:event_btnConfirmarEnvioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new VentanaEnvio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPaquete;
    private javax.swing.JButton btnConfirmarEnvio;
    private javax.swing.JButton btnQuitarPaquete;
    private javax.swing.JLabel jCantidadPaquetes;
    private javax.swing.JTextField jEnvioNumero;
    private javax.swing.JFormattedTextField jFechaEnvio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jMontoTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPesoTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblFuncionariosVacia;
    private javax.swing.JLabel lblZonasVacia;
    private javax.swing.JList<Funcionario> lstListaFuncionarios;
    private javax.swing.JList<Paquete> lstListaPaquetesAEnviar;
    private javax.swing.JList<Paquete> lstListaPaquetesDisponibles;
    private javax.swing.JList<Zona> lstListaZonas;
    // End of variables declaration//GEN-END:variables
}
