/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Modelo.Observador;
import Modelo.Sistema;
import javax.swing.JOptionPane;

/**
 *
 * @author juand
 */
public class VentanaLogTransacciones extends javax.swing.JFrame implements Observador{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaLogTransacciones.class.getName());
    private Sistema sistema;
    /**
     * Creates new form VentanaLogTransacciones
     */
    public VentanaLogTransacciones(Sistema unSistema) {
        initComponents();
        sistema = unSistema;
        sistema.agregarObservador(this);
        cargarLog();
    }
    public void cargarLog(){
        java.util.ArrayList<String> lineas = sistema.obtenerLogTransacciones();
        lstLogTransacciones.setListData(lineas.toArray(new String[0]));
        if (lineas.isEmpty()) {
            lblLogVacio.setVisible(true);
        } else {
            lblLogVacio.setVisible(false);
        }
    }
    
    @Override
    public void actualizar(){
        cargarLog();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLogTransacciones = new javax.swing.JList<>();
        btnBorrarLog = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblLogVacio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lstLogTransacciones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstLogTransacciones);

        btnBorrarLog.setText("Borrar");
        btnBorrarLog.addActionListener(this::btnBorrarLogActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Log de Transacciones");

        lblLogVacio.setText("Lista Logs VACÍA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogVacio)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnBorrarLog)))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnBorrarLog)))
                .addGap(18, 18, 18)
                .addComponent(lblLogVacio)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 380, 280);

        setBounds(0, 0, 416, 309);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarLogActionPerformed
        int opcionElegida = JOptionPane.showConfirmDialog(this,
                "¿Está seguro que desea borrar todo el contenido del log de transacciones?",
                "Confirmar borrado",
                JOptionPane.YES_NO_OPTION);
        boolean confirmado = (opcionElegida == JOptionPane.YES_OPTION);
        if(confirmado){
            sistema.borrarLogTransacciones();
            cargarLog();
        }
    }//GEN-LAST:event_btnBorrarLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new VentanaLogTransacciones().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogVacio;
    private javax.swing.JList<String> lstLogTransacciones;
    // End of variables declaration//GEN-END:variables
}
