package Interfaz;
import Modelo.Observador;
import Modelo.Sistema;
import Modelo.Paquete;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author juand
 */
public class VentanaIngresoPaquetesSig extends javax.swing.JFrame implements Observador{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaIngresoPaquetesSig.class.getName());
    private Sistema sistema;
    private static VentanaIngresoPaquetesSig instancia;
  
    
    public VentanaIngresoPaquetesSig(Sistema unSistema) {
        initComponents();
        sistema = unSistema;
        instancia = this;
        sistema.agregarObservador(this);
        cargarTablaPaquetes();
    }
    private void cargarTablaPaquetes() {
        String[] columnas = {"Identificador", "Fecha", "Destinatario", "Departamento", "Peso (g)", "Estado", "Precio"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        ArrayList<Paquete> paquetes = sistema.getListaPaquetes();
        int i = 0;
        while (i < paquetes.size()) {
            Paquete p = paquetes.get(i);
            Object[] fila = {p.getIdentificador(), p.getFecha(), p.getDestinatario(),
                p.getDepartamentoDestino().getNombre(), p.getPeso(), p.getEstado(), p.getPrecio()};
            modelo.addRow(fila);
            i = i + 1;
        }
        jTablaPaquetes.setModel(modelo);
    }
    
    public static VentanaIngresoPaquetesSig getInstancia(){
        return instancia;
    }
    @Override
    public void actualizar(){
        cargarTablaPaquetes();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaPaquetes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jTablaPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablaPaquetes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 470, 280);

        setBounds(0, 0, 504, 309);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        instancia = null;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new VentanaIngresoPaquetesSig().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaPaquetes;
    // End of variables declaration//GEN-END:variables
}
