/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Modelo.Envio;
import Modelo.Observador;
import Modelo.Paquete;
import Modelo.Sistema;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
/**
 *
 * @author juand
 */
public class VentanaRecepcion extends javax.swing.JFrame implements Observador{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaRecepcion.class.getName());
    private Sistema sistema;
    /**
     * Creates new form VentanaRecepcion
     */
    public VentanaRecepcion(Sistema unSistema) {
        initComponents();
        sistema = unSistema;
        sistema.agregarObservador(this);
        cargarDatosIniciales();
    }
    
    private void cargarDatosIniciales(){
        ArrayList<Envio> envios = sistema.obtenerEnviosOrdenados();
        Envio[] arregloEnvios = envios.toArray(new Envio[0]);
        lstListaEnvios.setListData(arregloEnvios);
        lstListaEnvios.setCellRenderer(new RenderizadorEnvios());
        if (envios.isEmpty()) {
            lblEnviosVacia.setVisible(true);
        } else {
            lblEnviosVacia.setVisible(false);
        }
    }
    
    //Fuente:
    //https://docs.oracle.com/javase/tutorial/uiswing/components/combobox.html#renderer
    //docs.oracle.com/javase/tutorial/uiswing/components/list.html
    private class RenderizadorEnvios extends DefaultListCellRenderer {
        @Override
        public Component getListCellRendererComponent(JList<?> lista, Object valor, int indice, boolean seleccionado, boolean tieneFoco) {
            Component componente = super.getListCellRendererComponent(lista, valor, indice, seleccionado, tieneFoco);
            Envio envio = (Envio) valor;
            Color colorBase;
            if (envio.isRecepcionado()) {
                colorBase = Color.GREEN;
            } else {
                colorBase = Color.YELLOW;
            }
            if (seleccionado) {
                componente.setBackground(colorBase.darker());
            } else {
                componente.setBackground(colorBase);
            }
            return componente;
        }
    }
    @Override
    public void actualizar(){
        cargarDatosIniciales();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstListaEnvios = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstListaResultante = new javax.swing.JList<>();
        btnConfirmarRecepcion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblEnviosVacia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(320, 180));

        lstListaEnvios.addListSelectionListener(this::lstListaEnviosValueChanged);
        jScrollPane1.setViewportView(lstListaEnvios);

        jLabel1.setText("Lista Envios");

        jScrollPane2.setViewportView(lstListaResultante);

        btnConfirmarRecepcion.setText("Confirmar Recepcion");
        btnConfirmarRecepcion.addActionListener(this::btnConfirmarRecepcionActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Recepción");

        lblEnviosVacia.setText("Lista Envíos VACÍA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirmarRecepcion)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblEnviosVacia)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEnviosVacia)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmarRecepcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 380, 550);

        setBounds(0, 0, 416, 576);
    }// </editor-fold>//GEN-END:initComponents

    private void lstListaEnviosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstListaEnviosValueChanged
        Envio envioSeleccionado = lstListaEnvios.getSelectedValue();
        if (envioSeleccionado != null) {
            ArrayList<Paquete> paquetes = envioSeleccionado.getListaPaquetes();
            Paquete[] arregloPaquetes = paquetes.toArray(new Paquete[0]);
            lstListaResultante.setListData(arregloPaquetes);
            if (envioSeleccionado.isRecepcionado()) {
                lstListaResultante.setEnabled(false);
            } else {
                lstListaResultante.setEnabled(true);
                lstListaResultante.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
            }
        }
    }//GEN-LAST:event_lstListaEnviosValueChanged

    private void btnConfirmarRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarRecepcionActionPerformed
        Envio envioSeleccionado = lstListaEnvios.getSelectedValue();
        if (envioSeleccionado != null) {
            if (!envioSeleccionado.isRecepcionado()) {
                ArrayList<Paquete> paquetesEntregados = new ArrayList<Paquete>(lstListaResultante.getSelectedValuesList());
                if (paquetesEntregados.isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un paquete entregado.");
                } else {
                    sistema.confirmarRecepcion(envioSeleccionado, paquetesEntregados);
                    sistema.guardarSistema();
                    cargarDatosIniciales();
                    Paquete[] listaVacia = new Paquete[0];
                    lstListaResultante.setListData(listaVacia);
                }
            }
        }
    }//GEN-LAST:event_btnConfirmarRecepcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new VentanaRecepcion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarRecepcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEnviosVacia;
    private javax.swing.JList<Envio> lstListaEnvios;
    private javax.swing.JList<Paquete> lstListaResultante;
    // End of variables declaration//GEN-END:variables
}
