/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Modelo.Sistema;
import javax.swing.JOptionPane;
/**
 *
 * @author juand
 */
public class VentanaAltaFuncionario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaAltaFuncionario.class.getName());
    private Sistema sistema;
    private VentanaFuncionario ventanaFuncionario;
    /**
     * Creates new form VentanaAltaFuncionario
     */
    public VentanaAltaFuncionario(Sistema unSistema, VentanaFuncionario unaVentanaFuncionario) {
        sistema = unSistema;
        ventanaFuncionario = unaVentanaFuncionario;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAnoIngreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jNombreFuncionario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCelularFuncionario = new javax.swing.JTextField();
        jNumeroFuncionario = new javax.swing.JTextField();
        jAñoIngreso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRegistrarFuncionario = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jCargo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Registar Funcionario");

        jNombreFuncionario.setText("Nombre Funcionario");

        jLabel2.setText("Nombre");

        jCelularFuncionario.setText("Celular");

        jNumeroFuncionario.setText("Numero Funcionario");

        jAñoIngreso.setText("Año Ingreso");

        jLabel3.setText("Celular");

        jLabel4.setText("Numero Funcionario");

        jLabel5.setText("Año de Ingreso");

        btnRegistrarFuncionario.setText("Registrar");
        btnRegistrarFuncionario.addActionListener(this::btnRegistrarFuncionarioActionPerformed);

        jLabel6.setText("Cargo");

        jCargo.setText("Cargo");

        javax.swing.GroupLayout jAnoIngresoLayout = new javax.swing.GroupLayout(jAnoIngreso);
        jAnoIngreso.setLayout(jAnoIngresoLayout);
        jAnoIngresoLayout.setHorizontalGroup(
            jAnoIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAnoIngresoLayout.createSequentialGroup()
                .addGroup(jAnoIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jAnoIngresoLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1))
                    .addGroup(jAnoIngresoLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jAnoIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegistrarFuncionario)
                            .addGroup(jAnoIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addGroup(jAnoIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCelularFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNombreFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNumeroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAñoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jAnoIngresoLayout.setVerticalGroup(
            jAnoIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAnoIngresoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jAnoIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNombreFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jAnoIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCelularFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jAnoIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNumeroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jAnoIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jAñoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jAnoIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnRegistrarFuncionario)
                .addGap(35, 35, 35))
        );

        getContentPane().add(jAnoIngreso);
        jAnoIngreso.setBounds(10, 10, 380, 280);

        setBounds(0, 0, 416, 309);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarFuncionarioActionPerformed
        String nombre = jNombreFuncionario.getText();
        String celular = jCelularFuncionario.getText();
        String numeroFuncionario = jNumeroFuncionario.getText();
        String añoIngreso = jAñoIngreso.getText();
        String cargo = jCargo.getText();
        
        boolean datosNumericosValidos= sistema.verificarCaracteresNumericos(numeroFuncionario)&& sistema.verificarCaracteresNumericos(añoIngreso);
        if(datosNumericosValidos){
            int numeroFuncionarioInt = Integer.parseInt(numeroFuncionario);
            int añoIngresoInt = Integer.parseInt(añoIngreso);
            boolean registrado = sistema.registrarFuncionario(nombre, celular, numeroFuncionarioInt, añoIngresoInt, cargo);
            if(registrado){
            JOptionPane.showMessageDialog(this, "Funcionario agregado correctamente.");
            ventanaFuncionario.cargarListaFuncionarios();
            this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo agregar el funcionario. Verifique que los siguientes datos sean válidos y únicos: "
                        + "Nombre, celular, número de funcionario",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                }
        } else {
            JOptionPane.showMessageDialog(this,
            "El número de funcionario y el año de ingreso deben ser numéricos.",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_btnRegistrarFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new VentanaAltaFuncionario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarFuncionario;
    private javax.swing.JPanel jAnoIngreso;
    private javax.swing.JTextField jAñoIngreso;
    private javax.swing.JTextField jCargo;
    private javax.swing.JTextField jCelularFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jNombreFuncionario;
    private javax.swing.JTextField jNumeroFuncionario;
    // End of variables declaration//GEN-END:variables
}
