/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Modelo.Sistema;

/**
 *
 * @author juand
 */
public class VentanaInicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaInicial.class.getName());
    private Sistema sistema;
    /**
     * Creates new form VentanaInicial
     */
    public VentanaInicial(Sistema unSistema) {
        this.sistema = unSistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPanel = new javax.swing.JPanel();
        btnCargarSistema = new javax.swing.JRadioButton();
        btnNuevoSistema = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Comenzar con:");
        getContentPane().setLayout(null);

        pnlPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCargarSistema.setText("los datos de la última ejecución");
        btnCargarSistema.addActionListener(this::btnCargarSistemaActionPerformed);

        btnNuevoSistema.setText("un Sistema nuevo");
        btnNuevoSistema.addActionListener(this::btnNuevoSistemaActionPerformed);

        javax.swing.GroupLayout pnlPanelLayout = new javax.swing.GroupLayout(pnlPanel);
        pnlPanel.setLayout(pnlPanelLayout);
        pnlPanelLayout.setHorizontalGroup(
            pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCargarSistema)
                    .addComponent(btnNuevoSistema))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        pnlPanelLayout.setVerticalGroup(
            pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnCargarSistema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevoSistema)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        getContentPane().add(pnlPanel);
        pnlPanel.setBounds(20, 30, 350, 150);

        setBounds(0, 0, 416, 309);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarSistemaActionPerformed
        Sistema sistemaCargado = Sistema.cargarSistema();
        if (sistemaCargado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró un sistema guardado. Se iniciará uno nuevo.");
            sistemaCargado = new Sistema();
        }
        MenuPrincipal ventana = new MenuPrincipal(sistemaCargado);
        ventana.setVisible(true);
        this.dispose(); //cierro para evitar multiples instancias
    }//GEN-LAST:event_btnCargarSistemaActionPerformed

    private void btnNuevoSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoSistemaActionPerformed
        // TODO add your handling code here:
        Sistema sistema = new Sistema();
        MenuPrincipal ventana = new MenuPrincipal(sistema);
        ventana.setVisible(true);
        this.dispose(); //cierro para evitar multiples instancias
    }//GEN-LAST:event_btnNuevoSistemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new VentanaInicial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnCargarSistema;
    private javax.swing.JRadioButton btnNuevoSistema;
    private javax.swing.JPanel pnlPanel;
    // End of variables declaration//GEN-END:variables
}
