/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Modelo.Departamento;
import Modelo.Observador;
import Modelo.Paquete;
import Modelo.Sistema;
import Modelo.Zona;
import java.util.ArrayList;
import java.util.Iterator;
/**
 *
 * @author juand
 */
public class VentanaPaquetesPorEstado extends javax.swing.JFrame implements Observador{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPaquetesPorEstado.class.getName());
    private Sistema sistema;
    /**
     * Creates new form VentanaReportes
     */
    public VentanaPaquetesPorEstado(Sistema unSistema) {
        initComponents();
        sistema = unSistema;
        sistema.agregarObservador(this);
        cargarTabla();
    }
    
    private void cargarTabla(){
        javax.swing.table.DefaultTableModel modeloNombres = (javax.swing.table.DefaultTableModel) tablaNombresZonas.getModel();
        javax.swing.table.DefaultTableModel modeloDatos = (javax.swing.table.DefaultTableModel) tablaModelo.getModel();

        ArrayList<Zona> listaZonas = sistema.getListaZonas();

        int fila = 0;
        Iterator<Zona> iterador = listaZonas.iterator();
        while(iterador.hasNext()){
            Zona zona = iterador.next();
            modeloNombres.setValueAt(zona, fila, 0);
            int pendientes = sistema.contarPaquetesPorZonaYEstado(zona, "Pendiente");
            int enviados = sistema.contarPaquetesPorZonaYEstado(zona, "Enviado");
            int recibidos = sistema.contarPaquetesPorZonaYEstado(zona, "Recibido");
            int total = sistema.contarPaquetesPorZonaYEstado(zona, "Total");
            modeloDatos.setValueAt(pendientes, fila, 0);
            modeloDatos.setValueAt(enviados, fila, 1);
            modeloDatos.setValueAt(recibidos, fila, 2);
            modeloDatos.setValueAt(total, fila, 3);
            fila = fila + 1;
        }
    }
    

    private String obtenerEstadoPorColumna(int columna){
        String estado;
        if(columna == 0){
            estado = "Pendiente";
        }else if(columna == 1){
            estado = "Enviado";
        }else if(columna == 2){
            estado = "Recibido";
        }else{
            estado = "Total";
        }
        return estado;
    }

    private String armarMensajeDetalle(int cantidadClientes, ArrayList<Departamento> departamentos){
        String mensaje = "Cantidad de clientes distintos: " + cantidadClientes + "\n";
        mensaje = mensaje + "Departamentos de destino:\n";
        Iterator<Departamento> iterador = departamentos.iterator();
        while(iterador.hasNext()){
            Departamento departamento = iterador.next();
            mensaje = mensaje + "- " + departamento.getNombre() + "\n";
        }
        return mensaje;
    }
    
    private void mostrarInfoZona(Zona zona){
        int pendientes = sistema.contarPaquetesPorZonaYEstado(zona, "Pendiente");
        int enviados = sistema.contarPaquetesPorZonaYEstado(zona, "Enviado");
        int recibidos = sistema.contarPaquetesPorZonaYEstado(zona, "Recibido");
        boolean sinDatos = (pendientes == 0) && (enviados == 0) && (recibidos == 0);
        String mensaje;
        if (sinDatos) {
            mensaje = "Sin información";
        } else {
            mensaje = "Pendiente: " + pendientes + "\n" + "Enviado: " + enviados + "\n" + "Recibido: " + recibidos;
        }
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Datos de la zona " + zona.getNombre(), javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void resaltarZona(javax.swing.JLabel etiqueta){
        etiqueta.setBackground(new java.awt.Color(135, 206, 235));
    }

    private void restaurarColorZona(javax.swing.JLabel etiqueta){
        etiqueta.setBackground(new java.awt.Color(255, 194, 14));
    }
    
    @Override
    public void actualizar(){
        cargarTabla();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaModelo = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaNombresZonas = new javax.swing.JTable();
        panelMapa = new javax.swing.JPanel();
        etiquetaZonaNorte = new javax.swing.JLabel();
        etiquetaZonaOeste = new javax.swing.JLabel();
        etiquetaZonaEste = new javax.swing.JLabel();
        etiquetaZonaSur = new javax.swing.JLabel();
        etiquetaMapaUruguay = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tablaModelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Pendiente", "Enviado", "Recibido", "Total"
            }
        ));
        tablaModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaModeloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaModelo);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(160, 50, 375, 313);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tablaNombresZonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Zona"
            }
        ));
        tablaNombresZonas.setSurrendersFocusOnKeystroke(true);
        tablaNombresZonas.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(tablaNombresZonas);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 50, 117, 313);

        panelMapa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaZonaNorte.setBackground(new java.awt.Color(255, 194, 14));
        etiquetaZonaNorte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaZonaNorte.setText("NORTE");
        etiquetaZonaNorte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        etiquetaZonaNorte.setOpaque(true);
        etiquetaZonaNorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiquetaZonaNorteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiquetaZonaNorteMouseExited(evt);
            }
        });
        panelMapa.add(etiquetaZonaNorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        etiquetaZonaOeste.setBackground(new java.awt.Color(255, 194, 14));
        etiquetaZonaOeste.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaZonaOeste.setText("OESTE");
        etiquetaZonaOeste.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        etiquetaZonaOeste.setOpaque(true);
        etiquetaZonaOeste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiquetaZonaOesteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiquetaZonaOesteMouseExited(evt);
            }
        });
        panelMapa.add(etiquetaZonaOeste, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        etiquetaZonaEste.setBackground(new java.awt.Color(255, 194, 14));
        etiquetaZonaEste.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaZonaEste.setText("ESTE");
        etiquetaZonaEste.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        etiquetaZonaEste.setOpaque(true);
        etiquetaZonaEste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiquetaZonaEsteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiquetaZonaEsteMouseExited(evt);
            }
        });
        panelMapa.add(etiquetaZonaEste, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        etiquetaZonaSur.setBackground(new java.awt.Color(255, 194, 14));
        etiquetaZonaSur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaZonaSur.setText("SUR");
        etiquetaZonaSur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        etiquetaZonaSur.setOpaque(true);
        etiquetaZonaSur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiquetaZonaSurMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiquetaZonaSurMouseExited(evt);
            }
        });
        panelMapa.add(etiquetaZonaSur, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        etiquetaMapaUruguay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/mapa.png"))); // NOI18N
        etiquetaMapaUruguay.setText("jLabel1");
        panelMapa.add(etiquetaMapaUruguay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, 360));

        jPanel1.add(panelMapa);
        panelMapa.setBounds(40, 380, 400, 350);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Paquetes por Estado");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 10, 170, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 620, 900);

        setBounds(0, 0, 679, 800);
    }// </editor-fold>//GEN-END:initComponents

    private void tablaModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaModeloMouseClicked
        int fila = tablaModelo.getSelectedRow();
        int columna = tablaModelo.getSelectedColumn();
        if(fila != -1 && columna != -1){
            Zona zona = (Zona) tablaNombresZonas.getModel().getValueAt(fila, 0);
            String estado = obtenerEstadoPorColumna(columna);

            ArrayList<Paquete> paquetes = sistema.obtenerPaquetesPorZonaYEstado(zona, estado);
            int cantidadClientes = sistema.contarClientesDistintos(paquetes);
            ArrayList<Departamento> departamentos = sistema.obtenerDepartamentosDistintos(paquetes);

            String mensaje = armarMensajeDetalle(cantidadClientes, departamentos);
            javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Datos de la zona " + zona.getNombre(), javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_tablaModeloMouseClicked

    private void etiquetaZonaNorteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaZonaNorteMouseEntered
        Zona zona = sistema.buscarZona("Norte");
        resaltarZona(etiquetaZonaNorte);
        mostrarInfoZona(zona);
    }//GEN-LAST:event_etiquetaZonaNorteMouseEntered

    private void etiquetaZonaOesteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaZonaOesteMouseEntered
        Zona zona = sistema.buscarZona("Oeste");
        resaltarZona(etiquetaZonaOeste);
        mostrarInfoZona(zona);
        
    }//GEN-LAST:event_etiquetaZonaOesteMouseEntered

    private void etiquetaZonaEsteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaZonaEsteMouseEntered
        Zona zona = sistema.buscarZona("Este");
        resaltarZona(etiquetaZonaEste);
        mostrarInfoZona(zona);
    }//GEN-LAST:event_etiquetaZonaEsteMouseEntered

    private void etiquetaZonaSurMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaZonaSurMouseEntered
        Zona zona = sistema.buscarZona("Sur");
        resaltarZona(etiquetaZonaSur);
        mostrarInfoZona(zona);
        
    }//GEN-LAST:event_etiquetaZonaSurMouseEntered

    private void etiquetaZonaNorteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaZonaNorteMouseExited
        // TODO add your handling code here:
        restaurarColorZona(etiquetaZonaNorte);
    }//GEN-LAST:event_etiquetaZonaNorteMouseExited

    private void etiquetaZonaEsteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaZonaEsteMouseExited
        // TODO add your handling code here:
        restaurarColorZona(etiquetaZonaEste);
        
    }//GEN-LAST:event_etiquetaZonaEsteMouseExited

    private void etiquetaZonaSurMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaZonaSurMouseExited
        restaurarColorZona(etiquetaZonaSur);
    }//GEN-LAST:event_etiquetaZonaSurMouseExited

    private void etiquetaZonaOesteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaZonaOesteMouseExited
        restaurarColorZona(etiquetaZonaOeste);
    }//GEN-LAST:event_etiquetaZonaOesteMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new VentanaPaquetesPorEstado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaMapaUruguay;
    private javax.swing.JLabel etiquetaZonaEste;
    private javax.swing.JLabel etiquetaZonaNorte;
    private javax.swing.JLabel etiquetaZonaOeste;
    private javax.swing.JLabel etiquetaZonaSur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelMapa;
    private javax.swing.JTable tablaModelo;
    private javax.swing.JTable tablaNombresZonas;
    // End of variables declaration//GEN-END:variables
}
