/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Modelo.Cliente;
import Modelo.Sistema;
import Modelo.Observador;
import java.util.ArrayList;
/**
 *
 * @author juand
 */
public class VentanaCliente extends javax.swing.JFrame implements Observador{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaCliente.class.getName());
    private Sistema sistema;
    /**
     * Creates new form VentanaCliente
     */
    public VentanaCliente(Sistema unSistema) {
        initComponents();
        sistema = unSistema;
        sistema.agregarObservador(this);
        cargarListaClientes();
    }
    public void cargarListaClientes(){
        ArrayList<Cliente> clientes = sistema.obtenerClientesOrdenados();
        lstlistaClientes.setListData(clientes.toArray(new Cliente[0]));
        if(clientes.isEmpty()){
            lblClientesVacia.setVisible(true);
            jNombre.setVisible(false);
            jCelular.setVisible(false);
            jCorreo.setVisible(false);
        }else{
            lblClientesVacia.setVisible(false);
            jNombre.setVisible(true);
            jCelular.setVisible(true);
            jCorreo.setVisible(true);
        }
    }
    
    @Override
    public void actualizar(){
        cargarListaClientes();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstlistaClientes = new javax.swing.JList<>();
        btnAgregarCliente = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();
        jNombre = new javax.swing.JTextField();
        jCelular = new javax.swing.JTextField();
        jCorreo = new javax.swing.JTextField();
        lblClientesVacia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlCliente.setFocusTraversalPolicyProvider(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Clientes");

        lstlistaClientes.addListSelectionListener(this::lstlistaClientesValueChanged);
        jScrollPane1.setViewportView(lstlistaClientes);

        btnAgregarCliente.setText("Registrar Cliente");
        btnAgregarCliente.addActionListener(this::btnAgregarClienteActionPerformed);

        btnEditarCliente.setText("Guardar Cambios");
        btnEditarCliente.addActionListener(this::btnEditarClienteActionPerformed);

        jNombre.setText("Nombre");

        jCelular.setText("Celular");

        jCorreo.setText("Correo");

        lblClientesVacia.setText("Lista de clientes VACÍA");
        lblClientesVacia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlClienteLayout = new javax.swing.GroupLayout(pnlCliente);
        pnlCliente.setLayout(pnlClienteLayout);
        pnlClienteLayout.setHorizontalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClienteLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(379, 379, 379))
                            .addGroup(pnlClienteLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(jCelular)
                                    .addComponent(jCorreo))
                                .addGap(78, 78, 78))
                            .addGroup(pnlClienteLayout.createSequentialGroup()
                                .addComponent(btnAgregarCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditarCliente)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addComponent(lblClientesVacia)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlClienteLayout.setVerticalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblClientesVacia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarCliente)
                            .addComponent(btnEditarCliente))
                        .addGap(62, 62, 62))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(pnlCliente);
        pnlCliente.setBounds(10, 10, 410, 310);

        setBounds(0, 0, 445, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        VentanaAltaCliente ventanaAlta = new VentanaAltaCliente(sistema, this);
        ventanaAlta.setVisible(true);
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        Cliente clienteSeleccionado = lstlistaClientes.getSelectedValue();
        if (clienteSeleccionado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente de la lista",
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
            boolean modificado = sistema.modificarCliente(clienteSeleccionado.getNombre(),
                    jNombre.getText(), jCelular.getText(), jCorreo.getText());
            if(modificado){
                javax.swing.JOptionPane.showMessageDialog(this, "Cliente modificado correctamente");
                cargarListaClientes();
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo modificar el cliente. "
                        + "Verifique que el nombre y el celular sean válidos y únicos", "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    private void lstlistaClientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstlistaClientesValueChanged
        Cliente clienteSeleccionado = lstlistaClientes.getSelectedValue();
        if(clienteSeleccionado != null){
            jNombre.setText(clienteSeleccionado.getNombre());
            jCelular.setText(clienteSeleccionado.getCelular());
            jCorreo.setText(clienteSeleccionado.getCorreoElectronico());
        }
    }//GEN-LAST:event_lstlistaClientesValueChanged
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new VentanaCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JTextField jCelular;
    private javax.swing.JTextField jCorreo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClientesVacia;
    private javax.swing.JList<Cliente> lstlistaClientes;
    private javax.swing.JPanel pnlCliente;
    // End of variables declaration//GEN-END:variables
}
